In [3]:
import requests
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import time

In [4]:
print("Pandas:", pd.__version__)
print("NumPy:", np.__version__)

Pandas: 3.0.3
NumPy: 2.5.0

50 Indian cities + coordinates

In [5]:
cities = [
    {"city": "Delhi", "state": "Delhi", "lat": 28.6139, "lon": 77.2090},
    {"city": "Mumbai", "state": "Maharashtra", "lat": 19.0760, "lon": 72.8777},
    {"city": "Bengaluru", "state": "Karnataka", "lat": 12.9716, "lon": 77.5946},
    {"city": "Hyderabad", "state": "Telangana", "lat": 17.3850, "lon": 78.4867},
    {"city": "Chennai", "state": "Tamil Nadu", "lat": 13.0827, "lon": 80.2707},
    {"city": "Kolkata", "state": "West Bengal", "lat": 22.5726, "lon": 88.3639},
    {"city": "Pune", "state": "Maharashtra", "lat": 18.5204, "lon": 73.8567},
    {"city": "Ahmedabad", "state": "Gujarat", "lat": 23.0225, "lon": 72.5714},
    {"city": "Jaipur", "state": "Rajasthan", "lat": 26.9124, "lon": 75.7873},
    {"city": "Lucknow", "state": "Uttar Pradesh", "lat": 26.8467, "lon": 80.9462},

    {"city": "Bhubaneswar", "state": "Odisha", "lat": 20.2961, "lon": 85.8245},
    {"city": "Patna", "state": "Bihar", "lat": 25.5941, "lon": 85.1376},
    {"city": "Chandigarh", "state": "Chandigarh", "lat": 30.7333, "lon": 76.7794},
    {"city": "Bhopal", "state": "Madhya Pradesh", "lat": 23.2599, "lon": 77.4126},
    {"city": "Indore", "state": "Madhya Pradesh", "lat": 22.7196, "lon": 75.8577},
    {"city": "Nagpur", "state": "Maharashtra", "lat": 21.1458, "lon": 79.0882},
    {"city": "Surat", "state": "Gujarat", "lat": 21.1702, "lon": 72.8311},
    {"city": "Vadodara", "state": "Gujarat", "lat": 22.3072, "lon": 73.1812},
    {"city": "Rajkot", "state": "Gujarat", "lat": 22.3039, "lon": 70.8022},
    {"city": "Kochi", "state": "Kerala", "lat": 9.9312, "lon": 76.2673},

    {"city": "Thiruvananthapuram", "state": "Kerala", "lat": 8.5241, "lon": 76.9366},
    {"city": "Coimbatore", "state": "Tamil Nadu", "lat": 11.0168, "lon": 76.9558},
    {"city": "Madurai", "state": "Tamil Nadu", "lat": 9.9252, "lon": 78.1198},
    {"city": "Visakhapatnam", "state": "Andhra Pradesh", "lat": 17.6868, "lon": 83.2185},
    {"city": "Vijayawada", "state": "Andhra Pradesh", "lat": 16.5062, "lon": 80.6480},
    {"city": "Guwahati", "state": "Assam", "lat": 26.1445, "lon": 91.7362},
    {"city": "Ranchi", "state": "Jharkhand", "lat": 23.3441, "lon": 85.3096},
    {"city": "Raipur", "state": "Chhattisgarh", "lat": 21.2514, "lon": 81.6296},
    {"city": "Dehradun", "state": "Uttarakhand", "lat": 30.3165, "lon": 78.0322},
    {"city": "Shimla", "state": "Himachal Pradesh", "lat": 31.1048, "lon": 77.1734},

    {"city": "Srinagar", "state": "Jammu and Kashmir", "lat": 34.0837, "lon": 74.7973},
    {"city": "Jammu", "state": "Jammu and Kashmir", "lat": 32.7266, "lon": 74.8570},
    {"city": "Amritsar", "state": "Punjab", "lat": 31.6340, "lon": 74.8723},
    {"city": "Ludhiana", "state": "Punjab", "lat": 30.9010, "lon": 75.8573},
    {"city": "Varanasi", "state": "Uttar Pradesh", "lat": 25.3176, "lon": 82.9739},
    {"city": "Kanpur", "state": "Uttar Pradesh", "lat": 26.4499, "lon": 80.3319},
    {"city": "Agra", "state": "Uttar Pradesh", "lat": 27.1767, "lon": 78.0081},
    {"city": "Meerut", "state": "Uttar Pradesh", "lat": 28.9845, "lon": 77.7064},
    {"city": "Prayagraj", "state": "Uttar Pradesh", "lat": 25.4358, "lon": 81.8463},
    {"city": "Gaya", "state": "Bihar", "lat": 24.7914, "lon": 85.0002},

    {"city": "Jodhpur", "state": "Rajasthan", "lat": 26.2389, "lon": 73.0243},
    {"city": "Udaipur", "state": "Rajasthan", "lat": 24.5854, "lon": 73.7125},
    {"city": "Kota", "state": "Rajasthan", "lat": 25.2138, "lon": 75.8648},
    {"city": "Mysuru", "state": "Karnataka", "lat": 12.2958, "lon": 76.6394},
    {"city": "Mangaluru", "state": "Karnataka", "lat": 12.9141, "lon": 74.8560},
    {"city": "Nashik", "state": "Maharashtra", "lat": 19.9975, "lon": 73.7898},
    {"city": "Aurangabad", "state": "Maharashtra", "lat": 19.8762, "lon": 75.3433},
    {"city": "Jabalpur", "state": "Madhya Pradesh", "lat": 23.1815, "lon": 79.9864},
    {"city": "Cuttack", "state": "Odisha", "lat": 20.4625, "lon": 85.8830},
    {"city": "Rourkela", "state": "Odisha", "lat": 22.2604, "lon": 84.8536}
]

print("Total cities:", len(cities))

Total cities: 50

In [7]:


START_DATE = "2026-08-01"
END_DATE = "2026-09-14"

hourly_variables = [
    "pm2_5",
    "pm10",
    "carbon_monoxide",
    "nitrogen_dioxide",
    "sulphur_dioxide",
    "ozone",
    "us_aqi"
]

print(hourly_variables)

['pm2_5', 'pm10', 'carbon_monoxide', 'nitrogen_dioxide', 'sulphur_dioxide', 'ozone', 'us_aqi']

In [8]:
city = cities[0]

url = "https://air-quality-api.open-meteo.com/v1/air-quality"

params = {
    "latitude": city["lat"],
    "longitude": city["lon"],
    "hourly": ",".join(hourly_variables),
    "start_date": START_DATE,
    "end_date": END_DATE,
    "timezone": "Asia/Kolkata"
}

response = requests.get(url, params=params, timeout=60)

print("Status Code:", response.status_code)

Status Code: 200

In [9]:
data = response.json()

print("Available keys:")
print(data["hourly"].keys())

print("\nNumber of records:")
print(len(data["hourly"]["time"]))

Available keys:
dict_keys(['time', 'pm2_5', 'pm10', 'carbon_monoxide', 'nitrogen_dioxide', 'sulphur_dioxide', 'ozone', 'us_aqi'])

Number of records:
1080

In [11]:
def fetch_aqi_data(city_info, start_date, end_date):
    
    url = "https://air-quality-api.open-meteo.com/v1/air-quality"
    
    params = {
        "latitude": city_info["lat"],
        "longitude": city_info["lon"],
        "hourly": ",".join(hourly_variables),
        "start_date": start_date,
        "end_date": end_date,
        "timezone": "Asia/Kolkata"
    }
    
    response = requests.get(url, params=params, timeout=60)
    
    # API response check
    response.raise_for_status()
    
    data = response.json()
    
    # Convert hourly JSON to DataFrame
    df = pd.DataFrame(data["hourly"])
    
    # Add city information
    df["city"] = city_info["city"]
    df["state"] = city_info["state"]
    df["latitude"] = city_info["lat"]
    df["longitude"] = city_info["lon"]
    
    return df

In [12]:
test_df = fetch_aqi_data(
    cities[0],
    START_DATE,
    END_DATE
)

print("Shape:", test_df.shape)
print(test_df.head())

Shape: (1080, 12)
               time  pm2_5   pm10  carbon_monoxide  nitrogen_dioxide  \
0  2026-08-01T00:00   28.6   29.5            410.0              24.4
1  2026-08-01T01:00   41.2  157.9            358.0              21.2
2  2026-08-01T02:00   49.4  225.8            321.0              18.9
3  2026-08-01T03:00   52.9  252.4            299.0              18.2
4  2026-08-01T04:00   52.4  243.1            292.0              18.4

   sulphur_dioxide  ozone  us_aqi   city  state  latitude  longitude
0             19.2   59.0      89  Delhi  Delhi   28.6139     77.209
1             18.2   61.0      88  Delhi  Delhi   28.6139     77.209
2             17.7   62.0      88  Delhi  Delhi   28.6139     77.209
3             17.9   59.0      89  Delhi  Delhi   28.6139     77.209
4             18.6   56.0      91  Delhi  Delhi   28.6139     77.209

In [13]:
all_data = []

for i, city in enumerate(cities, start=1):
    
    print(f"Fetching {i}/{len(cities)}: {city['city']}")
    
    try:
        df_city = fetch_aqi_data(
            city,
            START_DATE,
            END_DATE
        )
        
        all_data.append(df_city)
        
        print(f"   Rows fetched: {len(df_city)}")
        
    except Exception as e:
        print(f"   ERROR: {e}")
    
    time.sleep(1)

Fetching 1/50: Delhi
   Rows fetched: 1080
Fetching 2/50: Mumbai
   Rows fetched: 1080
Fetching 3/50: Bengaluru
   Rows fetched: 1080
Fetching 4/50: Hyderabad
   Rows fetched: 1080
Fetching 5/50: Chennai
   Rows fetched: 1080
Fetching 6/50: Kolkata
   Rows fetched: 1080
Fetching 7/50: Pune
   Rows fetched: 1080
Fetching 8/50: Ahmedabad
   Rows fetched: 1080
Fetching 9/50: Jaipur
   Rows fetched: 1080
Fetching 10/50: Lucknow
   Rows fetched: 1080
Fetching 11/50: Bhubaneswar
   Rows fetched: 1080
Fetching 12/50: Patna
   Rows fetched: 1080
Fetching 13/50: Chandigarh
   Rows fetched: 1080
Fetching 14/50: Bhopal
   Rows fetched: 1080
Fetching 15/50: Indore
   Rows fetched: 1080
Fetching 16/50: Nagpur
   Rows fetched: 1080
Fetching 17/50: Surat
   Rows fetched: 1080
Fetching 18/50: Vadodara
   Rows fetched: 1080
Fetching 19/50: Rajkot
   Rows fetched: 1080
Fetching 20/50: Kochi
   Rows fetched: 1080
Fetching 21/50: Thiruvananthapuram
   Rows fetched: 1080
Fetching 22/50: Coimbatore
   Rows fetched: 1080
Fetching 23/50: Madurai
   Rows fetched: 1080
Fetching 24/50: Visakhapatnam
   Rows fetched: 1080
Fetching 25/50: Vijayawada
   Rows fetched: 1080
Fetching 26/50: Guwahati
   Rows fetched: 1080
Fetching 27/50: Ranchi
   Rows fetched: 1080
Fetching 28/50: Raipur
   Rows fetched: 1080
Fetching 29/50: Dehradun
   Rows fetched: 1080
Fetching 30/50: Shimla
   Rows fetched: 1080
Fetching 31/50: Srinagar
   Rows fetched: 1080
Fetching 32/50: Jammu
   Rows fetched: 1080
Fetching 33/50: Amritsar
   Rows fetched: 1080
Fetching 34/50: Ludhiana
   Rows fetched: 1080
Fetching 35/50: Varanasi
   Rows fetched: 1080
Fetching 36/50: Kanpur
   Rows fetched: 1080
Fetching 37/50: Agra
   Rows fetched: 1080
Fetching 38/50: Meerut
   Rows fetched: 1080
Fetching 39/50: Prayagraj
   Rows fetched: 1080
Fetching 40/50: Gaya
   Rows fetched: 1080
Fetching 41/50: Jodhpur
   Rows fetched: 1080
Fetching 42/50: Udaipur
   Rows fetched: 1080
Fetching 43/50: Kota
   Rows fetched: 1080
Fetching 44/50: Mysuru
   Rows fetched: 1080
Fetching 45/50: Mangaluru
   Rows fetched: 1080
Fetching 46/50: Nashik
   Rows fetched: 1080
Fetching 47/50: Aurangabad
   Rows fetched: 1080
Fetching 48/50: Jabalpur
   Rows fetched: 1080
Fetching 49/50: Cuttack
   Rows fetched: 1080
Fetching 50/50: Rourkela
   Rows fetched: 1080

In [14]:
aqi_raw = pd.concat(
    all_data,
    ignore_index=True
)

print("Final shape:", aqi_raw.shape)

Final shape: (54000, 12)

In [16]:
##Basic check
print("Cities:", aqi_raw["city"].nunique())
print("States:", aqi_raw["state"].nunique())

print("\nRows by city:")
print(aqi_raw["city"].value_counts())

Cities: 50
States: 22

Rows by city:
city
Delhi                 1080
Mumbai                1080
Bengaluru             1080
Hyderabad             1080
Chennai               1080
Kolkata               1080
Pune                  1080
Ahmedabad             1080
Jaipur                1080
Lucknow               1080
Bhubaneswar           1080
Patna                 1080
Chandigarh            1080
Bhopal                1080
Indore                1080
Nagpur                1080
Surat                 1080
Vadodara              1080
Rajkot                1080
Kochi                 1080
Thiruvananthapuram    1080
Coimbatore            1080
Madurai               1080
Visakhapatnam         1080
Vijayawada            1080
Guwahati              1080
Ranchi                1080
Raipur                1080
Dehradun              1080
Shimla                1080
Srinagar              1080
Jammu                 1080
Amritsar              1080
Ludhiana              1080
Varanasi              1080
Kanpur                1080
Agra                  1080
Meerut                1080
Prayagraj             1080
Gaya                  1080
Jodhpur               1080
Udaipur               1080
Kota                  1080
Mysuru                1080
Mangaluru             1080
Nashik                1080
Aurangabad            1080
Jabalpur              1080
Cuttack               1080
Rourkela              1080
Name: count, dtype: int64

In [17]:
###save data 
aqi_raw.to_csv(
    "india_aqi_raw_50cities.csv",
    index=False
)

print("Raw AQI data saved successfully.")

Raw AQI data saved successfully.

In [19]:
##Dataset  basic structure
print("Shape:", aqi_raw.shape)

print("\nColumns:")
print(aqi_raw.columns.tolist())

print("\nData Types:")
print(aqi_raw.dtypes)

Shape: (54000, 12)

Columns:
['time', 'pm2_5', 'pm10', 'carbon_monoxide', 'nitrogen_dioxide', 'sulphur_dioxide', 'ozone', 'us_aqi', 'city', 'state', 'latitude', 'longitude']

Data Types:
time                    str
pm2_5               float64
pm10                float64
carbon_monoxide     float64
nitrogen_dioxide    float64
sulphur_dioxide     float64
ozone               float64
us_aqi                int64
city                    str
state                   str
latitude            float64
longitude           float64
dtype: object

In [20]:
aqi_raw.head()

,time,pm2_5,pm10,carbon_monoxide,nitrogen_dioxide,sulphur_dioxide,ozone,us_aqi,city,state,latitude,longitude
0,2026-08-01T00:00,28.6,29.5,410.0,24.4,19.2,59.0,89,Delhi,Delhi,28.6139,77.209
1,2026-08-01T01:00,41.2,157.9,358.0,21.2,18.2,61.0,88,Delhi,Delhi,28.6139,77.209
2,2026-08-01T02:00,49.4,225.8,321.0,18.9,17.7,62.0,88,Delhi,Delhi,28.6139,77.209
3,2026-08-01T03:00,52.9,252.4,299.0,18.2,17.9,59.0,89,Delhi,Delhi,28.6139,77.209
4,2026-08-01T04:00,52.4,243.1,292.0,18.4,18.6,56.0,91,Delhi,Delhi,28.6139,77.209

In [21]:
##Last 5 rows
aqi_raw.tail()

,time,pm2_5,pm10,carbon_monoxide,nitrogen_dioxide,sulphur_dioxide,ozone,us_aqi,city,state,latitude,longitude
53995,2026-09-14T19:00,30.7,32.9,1585.0,19.0,13.4,92.0,105,Rourkela,Odisha,22.2604,84.8536
53996,2026-09-14T20:00,31.8,33.9,1707.0,23.4,16.0,81.0,96,Rourkela,Odisha,22.2604,84.8536
53997,2026-09-14T21:00,38.1,40.0,1608.0,29.1,17.7,66.0,96,Rourkela,Odisha,22.2604,84.8536
53998,2026-09-14T22:00,42.8,44.6,1371.0,35.2,19.0,48.0,97,Rourkela,Odisha,22.2604,84.8536
53999,2026-09-14T23:00,44.9,46.7,1118.0,38.8,20.5,35.0,98,Rourkela,Odisha,22.2604,84.8536

In [22]:
print("Number of cities:", aqi_raw["city"].nunique())

print("\nCities:")
print(sorted(aqi_raw["city"].unique()))

Number of cities: 50

Cities:
['Agra', 'Ahmedabad', 'Amritsar', 'Aurangabad', 'Bengaluru', 'Bhopal', 'Bhubaneswar', 'Chandigarh', 'Chennai', 'Coimbatore', 'Cuttack', 'Dehradun', 'Delhi', 'Gaya', 'Guwahati', 'Hyderabad', 'Indore', 'Jabalpur', 'Jaipur', 'Jammu', 'Jodhpur', 'Kanpur', 'Kochi', 'Kolkata', 'Kota', 'Lucknow', 'Ludhiana', 'Madurai', 'Mangaluru', 'Meerut', 'Mumbai', 'Mysuru', 'Nagpur', 'Nashik', 'Patna', 'Prayagraj', 'Pune', 'Raipur', 'Rajkot', 'Ranchi', 'Rourkela', 'Shimla', 'Srinagar', 'Surat', 'Thiruvananthapuram', 'Udaipur', 'Vadodara', 'Varanasi', 'Vijayawada', 'Visakhapatnam']

In [23]:
##Duplicate check
print("Total duplicate rows:", aqi_raw.duplicated().sum())

Total duplicate rows: 0

In [25]:
##city + time duplicate check

In [26]:
duplicate_city_time = aqi_raw.duplicated(
    subset=["city", "time"]
).sum()

print("Duplicate city-time records:", duplicate_city_time)

Duplicate city-time records: 0

In [27]:
##Missing values
missing = aqi_raw.isnull().sum()

print(missing)

time                0
pm2_5               0
pm10                0
carbon_monoxide     0
nitrogen_dioxide    0
sulphur_dioxide     0
ozone               0
us_aqi              0
city                0
state               0
latitude            0
longitude           0
dtype: int64

In [28]:
##Date/time check
print("First datetime:", aqi_raw["time"].min())
print("Last datetime:", aqi_raw["time"].max())

First datetime: 2026-08-01T00:00
Last datetime: 2026-09-14T23:00

In [29]:
aqi_raw.info()

<class 'pandas.DataFrame'>
RangeIndex: 54000 entries, 0 to 53999
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   time              54000 non-null  str
 1   pm2_5             54000 non-null  float64
 2   pm10              54000 non-null  float64
 3   carbon_monoxide   54000 non-null  float64
 4   nitrogen_dioxide  54000 non-null  float64
 5   sulphur_dioxide   54000 non-null  float64
 6   ozone             54000 non-null  float64
 7   us_aqi            54000 non-null  int64
 8   city              54000 non-null  str
 9   state             54000 non-null  str
 10  latitude          54000 non-null  float64
 11  longitude         54000 non-null  float64
dtypes: float64(8), int64(1), str(3)
memory usage: 4.9 MB

In [32]:
##coneert datetime
aqi_raw["time"] = pd.to_datetime(
    aqi_raw["time"]
)

In [33]:
print(aqi_raw["time"].dtype)

datetime64[us]

In [36]:
 aqi_raw.describe()

,time,pm2_5,pm10,carbon_monoxide,nitrogen_dioxide,sulphur_dioxide,ozone,us_aqi,latitude,longitude
count,54000,54000.000000,54000.000000,54000.000000,54000.000000,54000.000000,54000.000000,54000.000000,54000.000000,54000.000000
mean,2026-08-23 11:29:59.999999,24.163824,36.074291,311.543407,12.040598,10.049435,72.063685,79.510426,22.376256,78.422190
min,2026-08-01 00:00:00,0.700000,0.800000,78.000000,0.000000,0.000000,0.000000,15.000000,8.524100,70.802200
25%,2026-08-12 05:45:00,11.800000,16.600000,167.000000,4.300000,3.800000,43.000000,57.000000,19.076000,74.872300
50%,2026-08-23 11:30:00,19.400000,26.800000,252.000000,8.300000,6.400000,63.000000,72.000000,22.871050,77.310800
75%,2026-09-03 17:15:00,30.500000,41.800000,369.000000,15.100000,11.100000,92.000000,93.000000,26.449900,80.946200
max,2026-09-14 23:00:00,192.800000,687.300000,3302.000000,113.800000,146.300000,311.000000,418.000000,34.083700,91.736200
std,NaN,18.632200,38.655849,231.453573,12.123798,11.481964,39.809838,34.183841,6.295588,4.547476

Create a cleaned working dataset

In [38]:
# Create a separate cleaned dataset
aqi_clean = aqi_raw.copy()

# Extract date/time features
aqi_clean["date"] = aqi_clean["time"].dt.date
aqi_clean["year"] = aqi_clean["time"].dt.year
aqi_clean["month"] = aqi_clean["time"].dt.month
aqi_clean["day"] = aqi_clean["time"].dt.day
aqi_clean["hour"] = aqi_clean["time"].dt.hour
aqi_clean["day_of_week"] = aqi_clean["time"].dt.dayofweek

# Create readable day name
aqi_clean["day_name"] = aqi_clean["time"].dt.day_name()

print("Shape:", aqi_clean.shape)

print("\nNew columns:")
print(aqi_clean.columns.tolist())

print("\nSample:")
display(aqi_clean.head())

Shape: (54000, 19)

New columns:
['time', 'pm2_5', 'pm10', 'carbon_monoxide', 'nitrogen_dioxide', 'sulphur_dioxide', 'ozone', 'us_aqi', 'city', 'state', 'latitude', 'longitude', 'date', 'year', 'month', 'day', 'hour', 'day_of_week', 'day_name']

Sample:

,time,pm2_5,pm10,carbon_monoxide,nitrogen_dioxide,sulphur_dioxide,ozone,us_aqi,city,state,latitude,longitude,date,year,month,day,hour,day_of_week,day_name
0,2026-08-01 00:00:00,28.6,29.5,410.0,24.4,19.2,59.0,89,Delhi,Delhi,28.6139,77.209,2026-08-01,2026,8,1,0,5,Saturday
1,2026-08-01 01:00:00,41.2,157.9,358.0,21.2,18.2,61.0,88,Delhi,Delhi,28.6139,77.209,2026-08-01,2026,8,1,1,5,Saturday
2,2026-08-01 02:00:00,49.4,225.8,321.0,18.9,17.7,62.0,88,Delhi,Delhi,28.6139,77.209,2026-08-01,2026,8,1,2,5,Saturday
3,2026-08-01 03:00:00,52.9,252.4,299.0,18.2,17.9,59.0,89,Delhi,Delhi,28.6139,77.209,2026-08-01,2026,8,1,3,5,Saturday
4,2026-08-01 04:00:00,52.4,243.1,292.0,18.4,18.6,56.0,91,Delhi,Delhi,28.6139,77.209,2026-08-01,2026,8,1,4,5,Saturday

In [39]:
##Check the new features
print("Hour range:", aqi_clean["hour"].min(), "to", aqi_clean["hour"].max())
print("Month values:", sorted(aqi_clean["month"].unique()))
print("Day of week values:", sorted(aqi_clean["day_of_week"].unique()))
print("Day names:", aqi_clean["day_name"].unique())

Hour range: 0 to 23
Month values: [np.int32(8), np.int32(9)]
Day of week values: [np.int32(0), np.int32(1), np.int32(2), np.int32(3), np.int32(4), np.int32(5), np.int32(6)]
Day names: <StringArray>
['Saturday', 'Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday']
Length: 7, dtype: str

Create AQI Category
Now we add a business-friendly target category from us_aqi.
This is useful for EDA, visualization, and later classification ML.

In [40]:
def classify_aqi(aqi):
    if aqi <= 50:
        return "Good"
    elif aqi <= 100:
        return "Moderate"
    elif aqi <= 150:
        return "Unhealthy for Sensitive Groups"
    elif aqi <= 200:
        return "Unhealthy"
    elif aqi <= 300:
        return "Very Unhealthy"
    else:
        return "Hazardous"


aqi_clean["aqi_category"] = aqi_clean["us_aqi"].apply(classify_aqi)

print(aqi_clean[["us_aqi", "aqi_category"]].head(20))

    us_aqi                    aqi_category
0       89                        Moderate
1       88                        Moderate
2       88                        Moderate
3       89                        Moderate
4       91                        Moderate
5       92                        Moderate
6       91                        Moderate
7       91                        Moderate
8       91                        Moderate
9       91                        Moderate
10      92                        Moderate
11      93                        Moderate
12      93                        Moderate
13      94                        Moderate
14      94                        Moderate
15      99                        Moderate
16     120  Unhealthy for Sensitive Groups
17     134  Unhealthy for Sensitive Groups
18     144  Unhealthy for Sensitive Groups
19     144  Unhealthy for Sensitive Groups

In [41]:
##Then check the distribution:
print("\nAQI Category Distribution:")
print(aqi_clean["aqi_category"].value_counts())

print("\nAQI Category Percentage:")
print(
    (aqi_clean["aqi_category"].value_counts(normalize=True) * 100)
    .round(2)
)

AQI Category Distribution:
aqi_category
Moderate                          36366
Unhealthy for Sensitive Groups     7537
Good                               6989
Unhealthy                          2916
Very Unhealthy                      134
Hazardous                            58
Name: count, dtype: int64

AQI Category Percentage:
aqi_category
Moderate                          67.34
Unhealthy for Sensitive Groups    13.96
Good                              12.94
Unhealthy                          5.40
Very Unhealthy                     0.25
Hazardous                          0.11
Name: proportion, dtype: float64

In [42]:
# save the data in csv format
aqi_clean.to_csv("aqi_clean.csv", index=False)

In [43]:
aqi_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 54000 entries, 0 to 53999
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   time              54000 non-null  datetime64[us]
 1   pm2_5             54000 non-null  float64
 2   pm10              54000 non-null  float64
 3   carbon_monoxide   54000 non-null  float64
 4   nitrogen_dioxide  54000 non-null  float64
 5   sulphur_dioxide   54000 non-null  float64
 6   ozone             54000 non-null  float64
 7   us_aqi            54000 non-null  int64
 8   city              54000 non-null  str
 9   state             54000 non-null  str
 10  latitude          54000 non-null  float64
 11  longitude         54000 non-null  float64
 12  date              54000 non-null  object
 13  year              54000 non-null  int32
 14  month             54000 non-null  int32
 15  day               54000 non-null  int32
 16  hour              54000 non-null  int32
 17  day_of_week       54000 non-null  int32
 18  day_name          54000 non-null  str
 19  aqi_category      54000 non-null  str
dtypes: datetime64[us](1), float64(8), int32(5), int64(1), object(1), str(4)
memory usage: 7.2+ MB

In [44]:
aqi_clean.head()

,time,pm2_5,pm10,carbon_monoxide,nitrogen_dioxide,sulphur_dioxide,ozone,us_aqi,city,state,latitude,longitude,date,year,month,day,hour,day_of_week,day_name,aqi_category
0,2026-08-01 00:00:00,28.6,29.5,410.0,24.4,19.2,59.0,89,Delhi,Delhi,28.6139,77.209,2026-08-01,2026,8,1,0,5,Saturday,Moderate
1,2026-08-01 01:00:00,41.2,157.9,358.0,21.2,18.2,61.0,88,Delhi,Delhi,28.6139,77.209,2026-08-01,2026,8,1,1,5,Saturday,Moderate
2,2026-08-01 02:00:00,49.4,225.8,321.0,18.9,17.7,62.0,88,Delhi,Delhi,28.6139,77.209,2026-08-01,2026,8,1,2,5,Saturday,Moderate
3,2026-08-01 03:00:00,52.9,252.4,299.0,18.2,17.9,59.0,89,Delhi,Delhi,28.6139,77.209,2026-08-01,2026,8,1,3,5,Saturday,Moderate
4,2026-08-01 04:00:00,52.4,243.1,292.0,18.4,18.6,56.0,91,Delhi,Delhi,28.6139,77.209,2026-08-01,2026,8,1,4,5,Saturday,Moderate